import type { Metadata } from 'next'
import './globals.css'
import ThemeSetter from '@/components/ThemeSetter'
import Fonts from '@/components/Fonts'
import { cookies } from 'next/headers'
import { configuration } from '@/configuration'
import classNames from 'clsx'
import React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const getClassName = () => {
    const themeCookie = cookies().get('theme')?.value
    const theme = themeCookie ?? configuration.theme
    const dark = theme === 'dark'
    return classNames({
      dark
    })
  }
  return (
    <React.Fragment>
      <html lang="en" className={getClassName()}>
        <Fonts />
        <ThemeSetter />
        <body>{children}</body>
      </html>
    </React.Fragment>
  )
}
